version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: financial-management_app_1
      APP_PORT: 4200

  mongodb:
    image: mongo:7.0.5
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data/db:/data/db
    networks:
      default:
        aliases:
          - financial-management_mongodb_1

  api:
    build:
      context: ..
      dockerfile: server-node/Dockerfile
    restart: on-failure
    stop_grace_period: 1m
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://financial-management_mongodb_1:27017/financial-management
    ports:
      - "3010:3000"
    depends_on:
      - mongodb
    networks:
      default:
        aliases:
          - financial-management_api_1

  app:
    build:
      context: ..
      dockerfile: client/Dockerfile
    restart: on-failure
    stop_grace_period: 1m
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://${DEVICE_HOSTNAME}:3010/financial-release
    depends_on:
      - api
    networks:
      default:
        aliases:
          - financial-management_app_1
